baseURL = "https://georgekw.github.io/"
languageCode = "en-us"
title = "Tracy & Brian 2021"
publishDir = "docs"

DefaultContentLanguage = "no"
[languages]
  [languages.no]
    languageName = "Norwegian"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.zh]
    languageName = "Chinese"
    weight = 3