baseURL = "https://georgekw.github.io/"
languageCode = "en-us"
title = "Tone & George 2021"
publishDir = "docs"

DefaultContentLanguage = "no"
[languages]
  [languages.no]
    languageName = "Norsk"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.zh]
    languageName = "中文"
    weight = 3